### ISSUE TITLE
Running relcomp tests?

### ISSUE THREAD

**Issue by atondwal** [hopv/MoCHi#1]
I'm trying to run the relcomp tests from the POPL13 paper, but running `mochi` on e.g. `intro-ord2.ml` gives me an error message informing me that verification failed due to incompleteness in the underlying type system.

I have a few other tests (particularly `sum.ml` from https://github.com/ucsd-progsys/mist/tree/master/mochi-tests/) that used to work in the old [web demo](http://www.kb.is.s.u-tokyo.ac.jp/~uhiro/relcomp/) that I'm trying to get working.

I also tried running with `-relative-complete`, but this causes an assertion failure in the fpat interface. I also tried each with `-z3` and `-hoice`

Is there some other combination of flags or a specific commit of `mochi` that I should be using to run these tests?

**Comment by ryosu-sato** [comment]
Unfortunately, -relative-complete mode is not maintained now.
I'll take a look at the assertion failure in the fpat interface,
and get back to you soon if It seems easy to fix.

**Comment by atondwal** [comment]
Thanks! In the meantime (or if it's not an ways fix), any chance you have a
copy of the binary from the (now broken) old webdemo with
-relative-complete mode?

**Comment by ryosu-sato** [comment]
I temporarily made [the download page](https://www-kb.is.s.u-tokyo.ac.jp/~ryosuke/misc/download_relcomp/README).
I'll delete the page within a couple of weeks.

**Comment by ryosu-sato** [comment]
The option `-relative-complete` is still not working,
but the [web demo](http://www.kb.is.s.u-tokyo.ac.jp/~uhiro/relcomp/) is now working.
